### ISSUE TITLE
알고리즘 레퍼지를 생성만 하고 사용하지 않는 건에 대하여

### ISSUE THREAD

**Issue by tlsdnr1135** [Bae-Ji-Won/Algorithm#1]
알고리즘 레퍼지는 왜 생성만 하고 아무것도 안쓰시죠?

**Comment by Bae-Ji-Won** [comment]
> 알고리즘 레퍼지는 왜 생성만 하고 아무것도 안쓰시죠?

이제 알고리즘 공부 1일차 시작입니다 ㅎㅎ
